In [5]:
from acquire import get_telco_data
from prepare import prep_telco
import explore

ImportError: cannot import name 'prep_telco' from 'prepare' (/Users/mcrob99/codeup-data-science/classification-exercises/prepare.py)

In [2]:
telco = get_telco_data()

In [4]:
telco.head().T

,0,1,2,3,4
Unnamed: 0,0,1,2,3,4
customer_id,0002-ORFBO,0003-MKNFE,0004-TLHLJ,0011-IGKFF,0013-EXCHZ
gender,Female,Male,Male,Male,Female
senior_citizen,0,0,0,1,1
partner,Yes,No,No,Yes,Yes
dependents,Yes,No,No,No,No
tenure,9,9,4,13,3
phone_service,Yes,Yes,Yes,Yes,Yes
multiple_lines,No,Yes,No,No,No
internet_service_type_id,1,1,2,2,2
online_security,No,No,No,No,No
online_backup,Yes,No,No,Yes,No
device_protection,No,No,Yes,Yes,No
tech_support,Yes,No,No,No,Yes
streaming_tv,Yes,No,No,Yes,Yes
streaming_movies,No,Yes,No,Yes,No
contract_type_id,2,1,1,1,1
paperless_billing,Yes,No,Yes,Yes,Yes
payment_type_id,2,2,1,1,2
monthly_charges,65.6,59.9,73.9,98.0,83.9
total_charges,593.3,542.4,280.85,1237.85,267.4
churn,No,No,Yes,Yes,Yes